### TASK 1

In [1]:
import random 
import numpy as np

np.random.seed(42)

A = np.random.randint(1, 101, 100)

print("Array A:")
print(A)

Array A:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


In [2]:
print("Maximum Value: ",np.max(A))
print("Minimum Value: ",np.min(A))
print("Mean Value: ",np.mean(A))
print("Median Value: ",np.median(A))
print("Standard Deviation Value: ",np.std(A))

Maximum Value:  100
Minimum Value:  2
Mean Value:  51.54
Median Value:  54.0
Standard Deviation Value:  29.278463074417004


In [5]:
B = np.arange(1, 101)

print("Array B:")
print(B)

Array B:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [9]:
Zero = np.zeros((5,3))
One = np.ones((5,5))

print("Zeros array:", Zero)
print("Shape:", Zero.shape)
print("Data type:", Zero.dtype)
print("\n")
print("Ones array:", One)
print("Shape:", One.shape)
print("Data type:", One.dtype)

Zeros array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (5, 3)
Data type: float64


Ones array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (5, 5)
Data type: float64


In [14]:
Ls = np.linspace(0,10,5)
print(Ls)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
twoD = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(twoD)

print("Shape:", twoD.shape)
print("Number of dimensions:", twoD.ndim)

print("Element at row 2, column 3:", twoD[1, 2])
print("First row:", twoD[0])
print("Second row:", twoD[1])

print("First column:", twoD[:, 0])
print("Second column:", twoD[:, 1])

print("Sliced 2D array:")
print(twoD[0:2, 0:2])

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Element at row 2, column 3: 6
First row: [1 2 3]
Second row: [4 5 6]
First column: [1 4 7]
Second column: [2 5 8]
Sliced 2D array:
[[1 2]
 [4 5]]


In [17]:
threeD = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(threeD)

print("Shape:", threeD.shape)
print("Number of dimensions:", threeD.ndim)

print("Element at [0, 1, 2]:", threeD[0, 1, 2])

print("Rows of first block:")
print(threeD[0])

print("First column of all blocks:")
print(threeD[:, :, 0])

print("Sliced 3D array:")
print(threeD[0, :, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of dimensions: 3
Element at [0, 1, 2]: 6
Rows of first block:
[[1 2 3]
 [4 5 6]]
First column of all blocks:
[[ 1  4]
 [ 7 10]]
Sliced 3D array:
[[1 2 3]
 [4 5 6]]


In [19]:
ar = np.arange(1, 13)

print("Original 1D array:")
print(ar)

matrix = ar.reshape(3, 4)

print("\nMatrix after reshape:")
print(matrix)

flat = matrix.flatten()

print("nArray after flatten:")
print(flat)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Matrix after reshape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
nArray after flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### TASK 2